### ISSUE TITLE
Hard to read list view in Dolphin Emulator

### ISSUE THREAD

**Issue by Tichy** [tsujan/E17gtk#3] opened 2017-03-23 19:37 UTC
Hi, I'm a dolphin-emu user and I found that the list view of games is presented with a too bright background. I don't have this issue with other dark themes such as Vertex.
Looks like dolphin uses wxgtk as widget library, which relies upon gtk-2.
![shot-2017-03-23_20-21-08](https://cloud.githubusercontent.com/assets/2348771/24266840/7e8175f2-1008-11e7-8635-3407c05aee0b.jpg)

**Comment by tsujan** [comment] 2017-03-23 20:29
I saw such problems when I used gtk apps. In all cases, the issue was about dark themes in general and there were app settings/stylesheets that could fix it. If I find some free time, I'll install dolphin emu to see how the issue can be fixed.

**Comment by tsujan** [comment] 2017-03-25 16:35
I installed dolphin-emu but since I didn't want to install anything else, I couldn't see that list view. However, I noticed that toolltips had white background and weren't readable. I changed the theme to another dark theme and saw the same thing. So, unfortunately, the problem is most probably caused by hard-coded colors and nothing can be done by the theme to correct it. I couldn't find a color setting in the app either :(

**Comment by Tichy** [comment] 2017-03-25 16:59
![shot-2017-03-25_17-45-36](https://cloud.githubusercontent.com/assets/2348771/24324280/e596838c-1183-11e7-9487-cfe259046432.png)

I also thought that i the colours could be hardcoder, but if you look at this screenshot, you'll see that they are different and it seems that in my case I don't have problems with the tooltip background.
It seems a very different behaviour between our setups. I also tried to find where is the part that controls the colours in the lists view in your gtkrc and in the one from the other theme, but I wasn't able to... :-/

My versions are:
gtk2 2.24.31
wxgtk 3.0.2
dolphin-emu 1:5.0

Running on Arch linux

**Comment by tsujan** [comment] 2017-03-25 17:42
>  I also tried to find where is the part that controls the colours in the lists view in your gtkrc

In E17gtk, only the view color is light (with dark text on it). I think dolphin-emu uses the view bg color for the list view but doesn't use its black text. The other theme in your screenshot should use a dark view; hence the difference.

Please do this test: find this block:
````
style "view"
{
	# It's better not to have too bright text views.
	base[NORMAL] = "#ECECEC"
	text[NORMAL] = "#000000"
}
````
and change `base[NORMAL]` to "#000000" and `text[NORMAL]` to "#ffffff".

**Comment by tsujan** [comment] 2017-03-25 17:45
If I'm right, dolphin-emu uses the view color ("#ECECEC") for tooltip background too and the above-mentioned change should also fix that issue. However, *no app should do such a thing!*

**Comment by Tichy** [comment] 2017-03-25 18:42
I tried and it didn't change anything. I found that wxgtk 3 works with gtk3 and not gtk2 (although for some reason it's still a dependency)... So, the list view it renders is the one from the gtk3 theme.
If your distro supplies version of wxgtk < 3, this could explain our different behaviours.
My doubt was triggered by a very similar issue on Firefox, whish was ported to gtk 3 some time ago. I'll open a different issue for it.
My gtk3 version is 3.22.10

**Comment by tsujan** [comment] 2017-03-25 18:52
If dolphin-emu takes its style from gtk3, there shouldn't be any difference because E17gtk has light views with black text for both gtk2 and gtk3:

![gtk3](https://cloud.githubusercontent.com/assets/981076/24325197/451a69d6-11b1-11e7-9e30-4f03c962863f.png)

Now, to work around such wxgtk issues, I can make all views dark, as in most dark themes. In fact, light views in a dark theme can be seen as a feature (the second theme I used for testing had it too) but if gtk isn't always consistent, I'll change it.

**Comment by tsujan** [comment] 2017-03-25 18:53
BTW, do you know of any other app that has this issue?

**Comment by Tichy** [comment] 2017-03-25 19:26
As far as I tried, every other application's list views are fine. The only other that looks odd is Liferea which, anyway, is readable.
![shot-2017-03-25_20-25-43](https://cloud.githubusercontent.com/assets/2348771/24325438/4e7e51da-1199-11e7-857e-2085c12f4d82.png)

**Comment by tsujan** [comment] 2017-03-26 01:25
I looked into the problem and found that:

(1) wxgtk-3.0.2 is based on gtk2;
 
(2) The issue is caused by a new bug in the old gtk2 pixmap engine. The dark theme `Breath-Dark`, which is also based on the pixmap engine, shows the same symptom:

![pixmap](https://cloud.githubusercontent.com/assets/981076/24327528/ba854132-11e8-11e7-9e4d-ea3935774f54.png)

Gtk2 themes that aren't based on pixmap may not be affected.

**Comment by Tichy** [comment] 2017-03-26 01:38
![shot-2017-03-26_03-35-49](https://cloud.githubusercontent.com/assets/2348771/24327588/67f13592-11d5-11e7-8953-d5f2e41b595d.png)

Seems that the problem is now fixed anyway. Thanks.
I found that wxgtk is based on gtk3 here: https://en.wikipedia.org/wiki/WxWidgets#History

**Comment by tsujan** [comment] 2017-03-26 01:39
> Seems that the problem is now fixed anyway.

Strange!! Are tooltips readable now?

**Comment by tsujan** [comment] 2017-03-26 01:41
BTW, the latest wxgtk in AUR is [this](https://www.archlinux.org/packages/extra/x86_64/wxgtk/), which is gtk2 based.

**Comment by Tichy** [comment] 2017-03-26 01:58
I'm confused about which gtk version it uses... The issue looked like #4 (and I know that firefox uses gtk3) and it disappeared when you fixed the other issues.
Here https://bugs.archlinux.org/task/48145?project=1&cat%5B0%5D=2&string=wxgtk they say that wxwidgets 3 have both gtk2 and 3 as backend. It could be that it tries with gtk3 if present, otherwise it falls back to gtk2.
I have no problems with tooltips (see the "Stop" tooltip in my screenshot)... but I didn't have problems with them even before.

**Comment by tsujan** [comment] 2017-03-26 02:18
Yes, wxgtk can be compiled against gtk3 but it seems that the [Arch package](https://aur.archlinux.org/packages/wxgtk-gtk3/) is flagged out-of-date -- I don't know why.

As for Firefox, it has its own toolkit and uses gtk3 only for styling.

Anyway, good to know that the problem is fixed :) Closing this.

**Closed as completed by tsujan** 2017-03-26 02:18 UTC
